name: Rankup
version: "${version}"
main: sh.okx.rankup.RankupPlugin
author: Okx
depend: [Vault]
softdepend: [PlaceholderAPI, mcMMO, AdvancedAchievements, Towny, SuperbVote, VotingPlugin, LuckPerms]
api-version: 1.13
folia-supported: true

commands:
  rankup:
    permission: rankup.rankup
    description: Rankup.
  rankup3:
    description: View Rankup version and perform some administrative commands.
    # support the old command
    aliases: [pru]
  ranks:
    permission: rankup.ranks
    description: List all the ranks.
  prestige:
    permission: rankup.prestige
    description: Prestige.
  prestiges:
    permission: rankup.prestiges
    description: List all the prestiges.
  maxrankup:
    permission: rankup.maxrankup
    description: Rankup as much as possible.
permissions:
  rankup.*:
    children:
      rankup.rankup: true
      rankup.admin: true
      rankup.ranks: true
      rankup.prestige: true
      rankup.prestiges: true
      rankup.auto: true
      rankup.maxrankup: true
      rankup.noconfirm: true
  rankup.admin:
    children:
      # if a player can see if the plugin needs updating when they run /pru
      rankup.checkversion: true
      # if a player can run /pru reload
      rankup.reload: true
      # if a player can force rankup or prestige someone
      rankup.force: true
      # if a player receives notifications to update rankup when they log in.
      rankup.notify: true
      rankup.playtime: true
      rankup.noconfirm.other: true
    default: op
  rankup.rankup:
    default: true
  rankup.ranks:
    default: true
  rankup.prestige:
    default: true
  rankup.prestiges:
    default: true
  rankup.auto:
    default: true
  rankup.maxrankup:
    default: true
  rankup.noconfirm:
    default: true
  rankup.playtime:
    description: Use all /rankup3 playtime subcommands for anyone.
    children:
      rankup.playtime.get: true
    default: op
  rankup.playtime.get:
    description: Use /rankup3 playtime get for anyone.
    default: op